SchemaVersion: 1.0
Name: grua-booking
Actions:
  check_commit:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        Enabled: false
      Variables:
        - IS_RELEASE_COMMIT
    Configuration:
      Steps:
        - Run: |
            export TRIGGER_COMMIT_ID=$CATALYST_EVENT_SHA
            export COMMIT_MESSAGE="$(git log -n 1 $TRIGGER_COMMIT_ID --oneline)"
            export RELEASE_PREFIX='chore(release):'
            export IS_RELEASE_COMMIT=false
            if grep -q "$RELEASE_PREFIX" <<< "$COMMIT_MESSAGE"; then
              echo 'this is a release commit'
              export IS_RELEASE_COMMIT=true
            fi
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large

  build_and_commit:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
      Variables:
        - Name: IS_RELEASE_COMMIT
          Value: ${{ steps.check_commit.outputs.Variables.IS_RELEASE_COMMIT }}
    Outputs:
      AutoDiscoverReports:
        Enabled: false
      Artifacts:
        - Name: codebase
          Files:
            - "**/*"
    Configuration:
      Steps:
        - Run: |
            if $IS_RELEASE_COMMIT; then
              echo 'This is a release commit, skipping'
            else
              chmod +x release.sh && ./release.sh
            fi
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    DependsOn:
      - check_commit

  publish_blueprint:
    Identifier: aws/publish-blueprint-action@v1
    Inputs:
      Sources:
        - WorkflowSource
      Artifacts:
        - codebase
      Variables:
        - Name: IS_RELEASE_COMMIT
          Value: ${{ steps.check_commit.outputs.Variables.IS_RELEASE_COMMIT }}
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Configuration:
      InputArtifactName: codebase
      PackageJSONPath: package.json
      TimeoutInSeconds: "120"
      ArtifactPackagePath: dist/js/*.tgz
    DependsOn:
      - build_and_commit
      - check_commit
